name: Autobuild

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Autobuild

    runs-on: windows-latest
    env:
      IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Build Debug
      run: cargo build --verbose
    - name: Test Debug
      run: cargo test --verbose
    - name: Build Release
      run: cargo build -r --verbose
    - name: Test Release
      run: cargo test -r --verbose
